### ISSUE TITLE
Error while archiving for iTunes upload.

### ISSUE THREAD

**Issue by xicomtech** [wfleming/WFInstagramAPI#2] opened 2013-08-28 11:18 UTC
I followed every steps to integrate the API. It works fine on device but when I tried to Archive my app to upload it to app store it shows error as in attached image. Please help.
![screen shot 2013-08-28 at 4 46 38 pm](https://f.cloud.github.com/assets/818371/1041526/7ff3b712-0fd3-11e3-9b9d-3722c1052f0d.png)

**Comment by wfleming** [comment] 2013-08-28 13:33
In step 4 from the README, please make sure you've changed the Header Search Paths for all of the build configurations. E.g., in the Example App that's part of the repository, you can see that both the "Debug" & "Release" configurations have the search path set.

![screen shot 2013-08-28 at 09 29 16](https://f.cloud.github.com/assets/188402/1042166/e9d90f9e-0fe5-11e3-9e72-b014bc3b9863.png)

If that looks fine, you should probably check your scheme setup to double check which build configuration is being used for the "archive" action.

Offhand, that seems like the most likely culprit for your issue. If that doesn't help, please let me know.

And once this is figured out, I'd love to know what the name of your app is once it's released. It's very cool to see my little library getting used in something being released.

Best,
Will

**Comment by xicomtech** [comment] 2013-08-29 06:05
Hi Will,
I double checked my settings, everything is ok there. Also please note that everything is working fine when I run it on device directly. When I build the app then there is no issue but the problem arrises when I try to Archive it. Have a look at attached image.
![screen shot 2013-08-29 at 10 32 11 am](https://f.cloud.github.com/assets/818371/1047567/e1ae079e-1070-11e3-92c6-e160f66ea1a6.png)

**Comment by xicomtech** [comment] 2013-08-29 09:56
This setting worked for archiving the app.
![screen shot 2013-08-29 at 1 16 28 pm](https://f.cloud.github.com/assets/818371/1048682/29b05946-1091-11e3-836e-1dfeaf73c170.png)

**Comment by wfleming** [comment] 2013-08-29 18:25
What version of XCode are you running?

**Comment by xicomtech** [comment] 2013-09-03 11:03
I am using XCode version 4.6

**Comment by wfleming** [comment] 2013-09-03 22:54
Hi,

Can you please confirm that changing the header search path for your Release target fixed this for you, and you've successfully submitted your app to iTunes? I can't reproduce the issue on XCode 4.6.3 myself, and other projects don't seem affected, so if you've gotten it fixed in your individual case I'm inclined to think this might have been some specific configuration on your project.

**Comment by xicomtech** [comment] 2013-09-05 11:43
My app is waiting to be reviewed by Apple Review Team. Also, now I have updated my Xcode to 4.6.3 and the behaviour is same as I mentioned above. When I change Header Search Path to "$(BUILT_PRODUCTS_DIR)/../../WFInstagramAPI" for Release then Archiving is successful.

Note: Remember I am NOT talking about "Command + B" but Archiving only.  "Command + B" works fine for path "$(BUILT_PRODUCTS_DIR)/../WFInstagramAPI" in both Release/Debug modes.

**Closed as completed** 2015-01-06 16:09 UTC
